contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #metagen channel"
    url: https://nfcore.slack.com/channels/metagen
    about: Discussion about the nf-core/metagen pipeline
